version: 2

jobs:
  "server":
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/batch-9-Posto
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn --cwd server install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./server/.cache/yarn
      - run: yarn --cwd server test
      
  "client":
    docker:
       - image: circleci/node:10.16.0
    working_directory: ~/batch-9-Posto
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn --cwd client install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/client/.cache/yarn
      - run: yarn --cwd client test

workflows:
  version: 2
  build:
    jobs:
      - "server"
      - "client"